openapi: 3.2.0
info:
  title: Rate Quote API Standards API
  version: 1.0.0-public-preview
  contact:
    name: DSDC APIs Rate Quote Full Truckload
    url: https://github.com/dsdcapis/rate-quote-full-truckload
  license:
    name: DSDC Repository License
    url: https://github.com/dsdcapis/rate-quote-full-truckload/blob/main/LICENSE.md
  description: '# Overview


    The Rate Quote API provides a standard way to request freight rate quotes for

    Full Truckload (FTL) shipments.'
tags:
- name: Rate Quote API Standards
  description: Standards for the FTL Rate Quote API
paths:
  /v1/ratequote/app:
    post:
      tags:
      - Rate Quote API Standards
      summary: Create a rate quote
      operationId: createRateQuote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ./schemas/schemas.yaml#/components/schemas/RateQuoteRequest
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: ./schemas/schemas.yaml#/components/schemas/RateQuoteResponse
  /v1/ratequote/app/{quoteId}:
    get:
      tags:
      - Rate Quote API Standards
      summary: Get a rate quote
      operationId: getRateQuoteById
      parameters:
      - name: quoteId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: ./schemas/schemas.yaml#/components/schemas/RateQuoteResponse
