openapi: 3.2.0
info:
  title: In-Transit Visibility In Transit Visibility API
  version: 1.0.0-public-preview
  contact:
    name: DSDC APIs Full Truckload
    url: https://github.com/dsdcapis/full-truckload
  license:
    name: DSDC Repository License
    url: https://github.com/dsdcapis/full-truckload/blob/main/LICENSE.md
  description: '# Overview

    In-Transit Visibility is the capability to track freight movements through milestones, events and

    location updates in real time, from pickup to delivery.'
tags:
- name: In Transit Visibility API
paths: {}
webhooks:
  shipmentEvents:
    post:
      summary: Shipment events webhook (from Carrier -> Subscriber)
      description: We POST batches of events to your configured `endpointUrl`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: ./schemas/schemas.yaml#/components/schemas/EventBatch
      responses:
        '200':
          description: Acknowledged (no retry)
        '202':
          description: Accepted (no retry)
        default:
          $ref: ./schemas/schemas.yaml#/components/responses/UnexpectedError
      tags:
      - In Transit Visibility API
